import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Every path the app navigates to by name is a route of `src/app`.
 *
 * expo-router's typed routes would catch a wrong one, but their types are
 * generated by the dev server into `.expo/types` (ignored by git), so `tsc`
 * here checks nothing: a path written `/(tab)` for `/(tabs)` — the entry's and
 * the sign-in's redirect to the tab bar, a push's landing — would compile, and
 * on the phone the redirect would show «Unmatched route». So the paths are
 * read off the source — `href`, `pathname` and `router.push/replace/navigate`
 * with a literal — and each must be the URL of a file under `src/app`.
 */

const SRC = path.resolve(__dirname, '../..');
const APP = path.join(SRC, 'app');
const SOURCE = /\.(ts|tsx)$/;

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return entry.name === '__tests__' ? [] : sourceFiles(full);
    }
    return SOURCE.test(entry.name) ? [full] : [];
  });
}

/** A group such as `(tabs)` names no part of the URL, but may be written in a path. */
const GROUP = /^\(.+\)$/;

/**
 * The URLs a route file answers to: `(tabs)/index.tsx` is both `/(tabs)` and
 * `/`; layouts (`_layout`) and the router's own files (`+html`) are none.
 */
function urlsOf(file: string): string[] {
  const segments = path.relative(APP, file).replace(SOURCE, '').split(path.sep);
  const name = segments.at(-1) ?? '';
  if (name.startsWith('_') || name.startsWith('+')) {
    return [];
  }
  const parts = name === 'index' ? segments.slice(0, -1) : segments;
  return [`/${parts.join('/')}`, `/${parts.filter((part) => !GROUP.test(part)).join('/')}`];
}

const ROUTES = new Set(sourceFiles(APP).flatMap(urlsOf));

/** A literal path handed to the router: `href="/x"`, `pathname: '/x'`, `router.push('/x')`. */
const NAVIGATION =
  /(?:href=\{?|href:\s*|pathname:\s*|router\.(?:push|replace|navigate)\(\s*)(['"])(\/[^'"]*)\1/g;

const USES = sourceFiles(SRC).flatMap((file) =>
  [...readFileSync(file, 'utf8').matchAll(NAVIGATION)].map(([, , url]) => ({
    url,
    file: path.relative(SRC, file).split(path.sep).join('/'),
  })),
);

const PATHS = [...new Set(USES.map(({ url }) => url))].sort();

test('the scan finds the app’s navigation, the redirect to the tab bar among it', () => {
  expect(PATHS).toEqual(expect.arrayContaining(['/(tabs)', '/sign-in', '/supply/new']));
  expect(USES.filter(({ url }) => url === '/(tabs)').map(({ file }) => file)).toEqual(
    expect.arrayContaining(['app/index.tsx', 'app/sign-in.tsx', 'features/push/destination.ts']),
  );
});

test('a path that names no route is told apart from one that does', () => {
  expect(ROUTES.has('/(tabs)')).toBe(true);
  expect(ROUTES.has('/task/[id]/step/[stepId]')).toBe(true);
  expect(ROUTES.has('/(tab)')).toBe(false);
  expect(ROUTES.has('/supplies/new')).toBe(false);
});

test.each(PATHS)('%s is a route of src/app', (url) => {
  expect(ROUTES.has(url)).toBe(true);
});
